src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>MSB_Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Household</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MSB_Lane__c</fullName>
        <label>Lane Number</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>12</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>14</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>16</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>17</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>18</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>19</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>21</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>22</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>23</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>24</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>25</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>26</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>27</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>28</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>29</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>MSB_of_Members__c</fullName>
        <label># of Members</label>
        <summaryForeignKey>CampaignMember.CampaignId</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>MSB_Grade__c</fullName>
        <formula>TEXT(Contact.MSB_Grade__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Grade</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>MSB_Grade__c</fullName>
        <label>Grade</label>
        <picklist>
            <picklistValues>
                <fullName>Adult</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Kindergarten</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1st</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2nd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3rd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4th</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/BSA_LanesAssignment_Controller.cls
/*
*   @Class : BSA_LanesAssignment_Controller.cls
*
*   @Author         :   Gonzalo Abruña
*   @Created        :   21 April 2014
*   @Description    :   Apex controller class that will show all per lane, according to requirements of TopCoder
*                       challenge: http://www.topcoder.com/challenge-details/30042041/?type=&nocache=true#.U1Ptcv3lTeE
*
*      ----------------------------------------------------------------------------------------------------------------------------                                
*      Modification Log     : 
*      ----------------------------------------------------------------------------------------------------------------------------
*      Developer             Date                Description
*      ----------------------------------------------------------------------------------------------------------------------------   
*      Gonzalo Abruña        21 April 2014        Creation
*
*/
public class BSA_LanesAssignment_Controller{
	public Map<String, List<Campaign>> mapCampaignsPerLane{get;set;}
	public Map<String, Integer> mapNrParticipantsInLane{get;set;} //To know the number of participants per Lane
	public Map<Id, List<CampaignMember>> mapMembersPerCampaign{get;set;}
	public List<String> orderedLanes{get;set;} //Because maps are not ordered

	public BSA_LanesAssignment_Controller(){
		try{
			initOrderedLanes();
			showLanes();
		}catch(Exception e){
			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage());
        	ApexPages.addMessage(myMsg);
        	return;
		}
	}

	//Just set values from 1 to NUMBER_OF_LANES
	private void initOrderedLanes(){
		orderedLanes = new List<String>();
		for(integer i=1; i<=BSA_Utils.NUMBER_OF_LANES;i++)
			orderedLanes.add(String.valueOf(i));
	}

	//Populate values for listOfLanes that will be used by the Visualforce page
	public void showLanes(){
		initLaneCampaigns();
		mapMembersPerCampaign = new Map<Id, List<CampaignMember>>();

		for(Campaign c : [SELECT Id, Name, MSB_Lane__c, MSB_Household__c, MSB_of_Members__c, MSB_Household__r.Name,
                                            (SELECT Id, ContactId, Contact.Name, MSB_Grade__c FROM CampaignMembers ORDER BY MSB_Grade__c) //To calculate the grade of a Campaign
                                    FROM Campaign
                                    WHERE Parent.Name = :BSA_Utils.getParentCampaignName()
                                        AND Parent.RecordType.DeveloperName = :BSA_Utils.EVENT_RECTYPE_DEVNAME
                                        AND Status = :BSA_Utils.CAMPAIGN_STATUS
                                        AND RecordType.DeveloperName = :BSA_Utils.APPLICATION_RECTYPE_DEVNAME
                                        AND MSB_Lane__c != null
                                        AND MSB_of_Members__c > 0]){
			mapCampaignsPerLane.get(c.MSB_Lane__c).add(c);
			if(!mapMembersPerCampaign.containsKey(c.Id)){
				mapMembersPerCampaign.put(c.Id, new List<CampaignMember>());
			}
			if(c.CampaignMembers != null && !c.CampaignMembers.isEmpty()){
				mapNrParticipantsInLane.put(c.MSB_Lane__c, mapNrParticipantsInLane.get(c.MSB_Lane__c)+c.CampaignMembers.size());
				mapMembersPerCampaign.get(c.Id).addAll(c.CampaignMembers);
			}
		}
	}

	//Ensure that every Lane has a defined a key value for each lane to avoid null pointer exceptions
	private void initLaneCampaigns(){
		mapCampaignsPerLane = new Map<String, List<Campaign>>();
		mapNrParticipantsInLane = new Map<String, Integer>();

		for(integer i=1; i<=BSA_Utils.NUMBER_OF_LANES;i++){
			mapCampaignsPerLane.put(String.valueOf(i), new List<Campaign>());
			mapNrParticipantsInLane.put(String.valueOf(i), 0);
		}
	}

	//Re-run assignation algorithm
	public void reorganizeLanes(){
		try{
			BSA_Assigner.assignLanes();
			showLanes();
		}catch(Exception e){
			ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage());
        	ApexPages.addMessage(myMsg);
        	return;
		}
		ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Lanes recalculated successfully');
        ApexPages.addMessage(myMsg);
	}
}